-- ============================================================
-- NUTRYON MVP – SCRIPT COMPLETO PARA ORACLE APEX
-- Disciplina: Disruptive Architectures: IoT, IoB & Generative IA
-- FIAP – 2025
-- ============================================================
-- IMPORTANTE: Execute no SQL Workshop > SQL Commands
-- Cole e rode UM BLOCO DE CADA VEZ — o SQL Commands não aceita
-- múltiplos comandos separados por ponto e vírgula de uma vez.
-- ============================================================


-- ============================================================
-- BLOCO 1 – APAGAR TABELAS ANTIGAS
-- Cole e rode. Erros de "table not exists" são normais.
-- ============================================================

DROP TABLE REFEICAO_ITEM CASCADE CONSTRAINTS PURGE;
DROP TABLE REFEICAO CASCADE CONSTRAINTS PURGE;
DROP TABLE INGREDIENTE CASCADE CONSTRAINTS PURGE;
DROP TABLE CATEGORIA_INGREDIENTE CASCADE CONSTRAINTS PURGE;
DROP TABLE TIPO_REFEICAO CASCADE CONSTRAINTS PURGE;
DROP TABLE USUARIO CASCADE CONSTRAINTS PURGE;


-- ============================================================
-- BLOCO 2 – CRIAR TABELA USUARIO
-- ============================================================

CREATE TABLE USUARIO (
    ID_USUARIO  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOM_USUARIO VARCHAR2(100) NOT NULL,
    EMAIL       VARCHAR2(120) NOT NULL UNIQUE,
    DT_NASC     DATE,
    OBJETIVO    VARCHAR2(20) DEFAULT 'MANTER',
    META_KCAL   NUMBER DEFAULT 2000,
    META_PROT   NUMBER DEFAULT 150,
    META_CARB   NUMBER DEFAULT 250,
    META_GORD   NUMBER DEFAULT 65
)


-- ============================================================
-- BLOCO 3 – CRIAR TABELA TIPO_REFEICAO
-- ============================================================

CREATE TABLE TIPO_REFEICAO (
    ID_TIPO_REFEICAO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOM_TIPO         VARCHAR2(40) NOT NULL UNIQUE
)


-- ============================================================
-- BLOCO 4 – CRIAR TABELA CATEGORIA_INGREDIENTE
-- ============================================================

CREATE TABLE CATEGORIA_INGREDIENTE (
    ID_CATEGORIA  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOM_CATEGORIA VARCHAR2(60) NOT NULL UNIQUE
)


-- ============================================================
-- BLOCO 5 – CRIAR TABELA INGREDIENTE
-- Macros incorporados diretamente (kcal, proteína, carbo, gordura por 100g)
-- ============================================================

CREATE TABLE INGREDIENTE (
    ID_INGREDIENTE  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOM_INGREDIENTE VARCHAR2(120) NOT NULL UNIQUE,
    ID_CATEGORIA    NUMBER REFERENCES CATEGORIA_INGREDIENTE(ID_CATEGORIA),
    KCAL_100G       NUMBER DEFAULT 0,
    PROT_100G       NUMBER DEFAULT 0,
    CARB_100G       NUMBER DEFAULT 0,
    GORD_100G       NUMBER DEFAULT 0
)


-- ============================================================
-- BLOCO 6 – CRIAR TABELA REFEICAO
-- ============================================================

CREATE TABLE REFEICAO (
    ID_REFEICAO      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_USUARIO       NUMBER NOT NULL REFERENCES USUARIO(ID_USUARIO),
    DT_REF           DATE NOT NULL,
    ID_TIPO_REFEICAO NUMBER NOT NULL REFERENCES TIPO_REFEICAO(ID_TIPO_REFEICAO),
    OBS              VARCHAR2(200)
)


-- ============================================================
-- BLOCO 7 – CRIAR TABELA REFEICAO_ITEM
-- ============================================================

CREATE TABLE REFEICAO_ITEM (
    ID_ITEM        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_REFEICAO    NUMBER NOT NULL REFERENCES REFEICAO(ID_REFEICAO) ON DELETE CASCADE,
    ID_INGREDIENTE NUMBER NOT NULL REFERENCES INGREDIENTE(ID_INGREDIENTE),
    QTDE_G         NUMBER NOT NULL
)


-- ============================================================
-- BLOCO 8 – INSERIR TIPOS DE REFEIÇÃO
-- ============================================================

INSERT ALL
    INTO TIPO_REFEICAO (ID_TIPO_REFEICAO, NOM_TIPO) VALUES (100, 'CAFE DA MANHA')
    INTO TIPO_REFEICAO (ID_TIPO_REFEICAO, NOM_TIPO) VALUES (101, 'ALMOCO')
    INTO TIPO_REFEICAO (ID_TIPO_REFEICAO, NOM_TIPO) VALUES (102, 'LANCHE')
    INTO TIPO_REFEICAO (ID_TIPO_REFEICAO, NOM_TIPO) VALUES (103, 'JANTAR')
SELECT 1 FROM DUAL


-- ============================================================
-- BLOCO 9 – INSERIR CATEGORIAS
-- ============================================================

INSERT ALL
    INTO CATEGORIA_INGREDIENTE (ID_CATEGORIA, NOM_CATEGORIA) VALUES (100, 'CEREAL')
    INTO CATEGORIA_INGREDIENTE (ID_CATEGORIA, NOM_CATEGORIA) VALUES (101, 'CARNE')
    INTO CATEGORIA_INGREDIENTE (ID_CATEGORIA, NOM_CATEGORIA) VALUES (102, 'FRUTA')
    INTO CATEGORIA_INGREDIENTE (ID_CATEGORIA, NOM_CATEGORIA) VALUES (103, 'LATICINIOS')
SELECT 1 FROM DUAL


-- ============================================================
-- BLOCO 10 – INSERIR INGREDIENTES COM MACROS
-- Valores nutricionais por 100g baseados na Tabela TACO
-- ============================================================

INSERT ALL
    INTO INGREDIENTE (ID_INGREDIENTE, NOM_INGREDIENTE, ID_CATEGORIA, KCAL_100G, PROT_100G, CARB_100G, GORD_100G)
        VALUES (100, 'ARROZ BRANCO COZIDO', 100, 128, 2.5, 28.1, 0.2)
    INTO INGREDIENTE (ID_INGREDIENTE, NOM_INGREDIENTE, ID_CATEGORIA, KCAL_100G, PROT_100G, CARB_100G, GORD_100G)
        VALUES (101, 'FEIJAO COZIDO', 100, 77, 5.0, 14.0, 0.5)
    INTO INGREDIENTE (ID_INGREDIENTE, NOM_INGREDIENTE, ID_CATEGORIA, KCAL_100G, PROT_100G, CARB_100G, GORD_100G)
        VALUES (102, 'FRANGO GRELHADO', 101, 159, 32.0, 0.0, 3.6)
    INTO INGREDIENTE (ID_INGREDIENTE, NOM_INGREDIENTE, ID_CATEGORIA, KCAL_100G, PROT_100G, CARB_100G, GORD_100G)
        VALUES (103, 'OVO COZIDO', 101, 155, 13.0, 1.1, 11.0)
    INTO INGREDIENTE (ID_INGREDIENTE, NOM_INGREDIENTE, ID_CATEGORIA, KCAL_100G, PROT_100G, CARB_100G, GORD_100G)
        VALUES (104, 'BANANA', 102, 89, 1.1, 22.8, 0.3)
    INTO INGREDIENTE (ID_INGREDIENTE, NOM_INGREDIENTE, ID_CATEGORIA, KCAL_100G, PROT_100G, CARB_100G, GORD_100G)
        VALUES (105, 'LEITE INTEGRAL', 103, 60, 3.2, 4.7, 3.3)
SELECT 1 FROM DUAL


-- ============================================================
-- BLOCO 11 – INSERIR USUÁRIOS COM METAS
-- ============================================================

INSERT ALL
    INTO USUARIO (ID_USUARIO, NOM_USUARIO, EMAIL, DT_NASC, OBJETIVO, META_KCAL, META_PROT, META_CARB, META_GORD)
        VALUES (100, 'Carlos Lima', 'carlos@fiap.com', DATE '1998-03-22', 'GANHAR', 2800, 180, 320, 70)
    INTO USUARIO (ID_USUARIO, NOM_USUARIO, EMAIL, DT_NASC, OBJETIVO, META_KCAL, META_PROT, META_CARB, META_GORD)
        VALUES (101, 'Ana Silva', 'ana@fiap.com', DATE '1995-05-10', 'PERDER', 1600, 130, 160, 50)
    INTO USUARIO (ID_USUARIO, NOM_USUARIO, EMAIL, DT_NASC, OBJETIVO, META_KCAL, META_PROT, META_CARB, META_GORD)
        VALUES (102, 'Maria Santos', 'maria@fiap.com', DATE '2001-07-15', 'MANTER', 2000, 150, 220, 60)
SELECT 1 FROM DUAL


-- ============================================================
-- BLOCO 12 – INSERIR REFEIÇÕES
-- ============================================================

INSERT ALL
    INTO REFEICAO (ID_REFEICAO, ID_USUARIO, DT_REF, ID_TIPO_REFEICAO, OBS)
        VALUES (100, 100, TRUNC(SYSDATE)+7/24,  100, 'Cafe do Carlos')
    INTO REFEICAO (ID_REFEICAO, ID_USUARIO, DT_REF, ID_TIPO_REFEICAO, OBS)
        VALUES (101, 100, TRUNC(SYSDATE)+12/24, 101, 'Almoco do Carlos')
    INTO REFEICAO (ID_REFEICAO, ID_USUARIO, DT_REF, ID_TIPO_REFEICAO, OBS)
        VALUES (102, 101, TRUNC(SYSDATE)+15/24, 102, 'Lanche da Ana')
    INTO REFEICAO (ID_REFEICAO, ID_USUARIO, DT_REF, ID_TIPO_REFEICAO, OBS)
        VALUES (103, 102, TRUNC(SYSDATE)+19/24, 103, 'Jantar da Maria')
SELECT 1 FROM DUAL


-- ============================================================
-- BLOCO 13 – INSERIR ITENS DAS REFEIÇÕES
-- ============================================================

INSERT ALL
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (100, 100, 102, 150)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (101, 100, 103, 100)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (102, 101, 102, 200)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (103, 101, 100, 150)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (104, 101, 101, 100)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (105, 102, 104, 120)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (106, 103, 102, 180)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (107, 103, 100, 130)
SELECT 1 FROM DUAL


-- ============================================================
-- BLOCO 14 – COMMIT
-- ============================================================

COMMIT


-- ============================================================
-- BLOCO 15 – VIEW: DASHBOARD DO USUÁRIO
-- Consumo do dia vs meta calórica
-- ============================================================

CREATE OR REPLACE VIEW VW_DASHBOARD_USUARIO AS
SELECT
    u.ID_USUARIO,
    u.NOM_USUARIO,
    u.OBJETIVO,
    u.META_KCAL,
    ROUND(NVL(SUM(i.KCAL_100G * ri.QTDE_G / 100), 0))                                   AS KCAL_CONSUMIDA,
    ROUND(u.META_KCAL - NVL(SUM(i.KCAL_100G * ri.QTDE_G / 100), 0))                     AS KCAL_RESTANTE,
    ROUND(NVL(SUM(i.PROT_100G * ri.QTDE_G / 100), 0), 1)                                 AS PROT_CONSUMIDA,
    ROUND(NVL(SUM(i.CARB_100G * ri.QTDE_G / 100), 0), 1)                                 AS CARB_CONSUMIDA,
    ROUND(NVL(SUM(i.GORD_100G * ri.QTDE_G / 100), 0), 1)                                 AS GORD_CONSUMIDA,
    ROUND(NVL(SUM(i.KCAL_100G * ri.QTDE_G / 100), 0) / NULLIF(u.META_KCAL,0) * 100, 1)  AS PCT_META
FROM USUARIO u
LEFT JOIN REFEICAO r
    ON r.ID_USUARIO = u.ID_USUARIO
    AND TRUNC(r.DT_REF) = TRUNC(SYSDATE)
LEFT JOIN REFEICAO_ITEM ri ON ri.ID_REFEICAO   = r.ID_REFEICAO
LEFT JOIN INGREDIENTE   i  ON i.ID_INGREDIENTE = ri.ID_INGREDIENTE
GROUP BY u.ID_USUARIO, u.NOM_USUARIO, u.OBJETIVO, u.META_KCAL


-- ============================================================
-- BLOCO 16 – VIEW: HISTÓRICO DE REFEIÇÕES
-- Todas as refeições com macros calculados automaticamente
-- ============================================================

CREATE OR REPLACE VIEW VW_HISTORICO_REFEICOES AS
SELECT
    u.NOM_USUARIO,
    t.NOM_TIPO                                   AS TIPO_REFEICAO,
    TO_CHAR(r.DT_REF, 'DD/MM/YYYY HH24:MI')      AS DATA_HORA,
    i.NOM_INGREDIENTE,
    ri.QTDE_G                                    AS QUANTIDADE_G,
    ROUND(i.KCAL_100G * ri.QTDE_G / 100, 1)      AS KCAL,
    ROUND(i.PROT_100G * ri.QTDE_G / 100, 1)      AS PROTEINA_G,
    ROUND(i.CARB_100G * ri.QTDE_G / 100, 1)      AS CARBO_G,
    ROUND(i.GORD_100G * ri.QTDE_G / 100, 1)      AS GORDURA_G,
    r.OBS
FROM REFEICAO r
JOIN USUARIO       u  ON u.ID_USUARIO       = r.ID_USUARIO
JOIN TIPO_REFEICAO t  ON t.ID_TIPO_REFEICAO = r.ID_TIPO_REFEICAO
JOIN REFEICAO_ITEM ri ON ri.ID_REFEICAO     = r.ID_REFEICAO
JOIN INGREDIENTE   i  ON i.ID_INGREDIENTE   = ri.ID_INGREDIENTE
ORDER BY r.DT_REF DESC


-- ============================================================
-- BLOCO 17 – VIEW: SUGESTÕES IA
-- Ingredientes mais frequentes por tipo de refeição
-- com percentual de confiança calculado por SQL analítico
-- ============================================================

CREATE OR REPLACE VIEW VW_SUGESTOES_REFEICAO AS
SELECT
    t.NOM_TIPO                                                                 AS TIPO_REFEICAO,
    i.NOM_INGREDIENTE                                                          AS ALIMENTO_SUGERIDO,
    COUNT(*)                                                                   AS FREQUENCIA,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY t.NOM_TIPO), 1) AS CONFIANCA_PCT,
    i.KCAL_100G,
    i.PROT_100G                                                                AS PROTEINAS_100G,
    i.CARB_100G                                                                AS CARBOIDRATOS_100G,
    i.GORD_100G                                                                AS GORDURAS_100G
FROM REFEICAO r
JOIN TIPO_REFEICAO t  ON t.ID_TIPO_REFEICAO = r.ID_TIPO_REFEICAO
JOIN REFEICAO_ITEM ri ON ri.ID_REFEICAO     = r.ID_REFEICAO
JOIN INGREDIENTE   i  ON i.ID_INGREDIENTE   = ri.ID_INGREDIENTE
GROUP BY t.NOM_TIPO, i.NOM_INGREDIENTE,
         i.KCAL_100G, i.PROT_100G, i.CARB_100G, i.GORD_100G
ORDER BY t.NOM_TIPO, FREQUENCIA DESC


-- ============================================================
-- BLOCO 18 – VERIFICAÇÃO FINAL
-- ============================================================

SELECT 'USUARIO'       AS TABELA, COUNT(*) AS REGISTROS FROM USUARIO      UNION ALL
SELECT 'INGREDIENTE',              COUNT(*)              FROM INGREDIENTE   UNION ALL
SELECT 'REFEICAO',                 COUNT(*)              FROM REFEICAO      UNION ALL
SELECT 'REFEICAO_ITEM',            COUNT(*)              FROM REFEICAO_ITEM


-- ============================================================
-- BLOCO 19 – TESTES DAS VIEWS (rode cada um separado)
-- ============================================================

SELECT NOM_USUARIO, OBJETIVO, META_KCAL,
       KCAL_CONSUMIDA, KCAL_RESTANTE, PCT_META || '%' AS PROGRESSO
FROM VW_DASHBOARD_USUARIO

SELECT NOM_USUARIO, TIPO_REFEICAO, NOM_INGREDIENTE,
       QUANTIDADE_G, KCAL, PROTEINA_G
FROM VW_HISTORICO_REFEICOES

SELECT TIPO_REFEICAO, ALIMENTO_SUGERIDO,
       CONFIANCA_PCT || '%' AS CONFIANCA, KCAL_100G
FROM VW_SUGESTOES_REFEICAO
