-- ============================================================
-- NUTRYON - DADOS COMPLEMENTARES PARA TREINAMENTO/DEMO DA IA
-- Execute depois de sql/nutryon_mvp.sql.
--
-- Objetivo:
-- 1. Expandir o catalogo de alimentos disponiveis no APEX.
-- 2. Aumentar o historico de refeicoes para que as sugestoes por
--    associacao aparecam de forma mais convincente no APEX e no video.
-- ============================================================

-- Catalogo expandido de categorias
MERGE INTO CATEGORIA_INGREDIENTE c
USING (
    SELECT 'VEGETAL' NOM_CATEGORIA FROM DUAL UNION ALL
    SELECT 'LEGUMINOSA' FROM DUAL UNION ALL
    SELECT 'OLEAGINOSA' FROM DUAL UNION ALL
    SELECT 'BEBIDA' FROM DUAL UNION ALL
    SELECT 'RAIZ' FROM DUAL UNION ALL
    SELECT 'PEIXE' FROM DUAL
) src
ON (c.NOM_CATEGORIA = src.NOM_CATEGORIA)
WHEN NOT MATCHED THEN
    INSERT (NOM_CATEGORIA)
    VALUES (src.NOM_CATEGORIA);

COMMIT;

-- Catalogo expandido de ingredientes e macros por 100g
MERGE INTO INGREDIENTE i
USING (
    SELECT 'AVEIA EM FLOCOS' nome, 'CEREAL' categoria, 394 kcal, 13.9 prot, 66.6 carb, 8.5 gord FROM DUAL UNION ALL
    SELECT 'PAO INTEGRAL', 'CEREAL', 253, 9.4, 49.9, 3.7 FROM DUAL UNION ALL
    SELECT 'TAPIOCA', 'CEREAL', 240, 0.2, 60.0, 0.0 FROM DUAL UNION ALL
    SELECT 'MACARRAO COZIDO', 'CEREAL', 158, 5.8, 30.9, 0.9 FROM DUAL UNION ALL
    SELECT 'BATATA DOCE COZIDA', 'RAIZ', 77, 0.6, 18.4, 0.1 FROM DUAL UNION ALL
    SELECT 'MANDIOCA COZIDA', 'RAIZ', 125, 0.6, 30.1, 0.3 FROM DUAL UNION ALL
    SELECT 'CARNE MOIDA MAGRA', 'CARNE', 219, 26.0, 0.0, 12.0 FROM DUAL UNION ALL
    SELECT 'PATINHO GRELHADO', 'CARNE', 219, 35.9, 0.0, 7.3 FROM DUAL UNION ALL
    SELECT 'PEITO DE PERU', 'CARNE', 104, 17.1, 1.5, 2.2 FROM DUAL UNION ALL
    SELECT 'SALMAO GRELHADO', 'PEIXE', 208, 22.1, 0.0, 12.4 FROM DUAL UNION ALL
    SELECT 'TILAPIA GRELHADA', 'PEIXE', 128, 26.0, 0.0, 2.7 FROM DUAL UNION ALL
    SELECT 'IOGURTE NATURAL', 'LATICINIOS', 61, 3.5, 4.7, 3.3 FROM DUAL UNION ALL
    SELECT 'QUEIJO MINAS', 'LATICINIOS', 264, 17.4, 3.2, 20.2 FROM DUAL UNION ALL
    SELECT 'WHEY PROTEIN', 'LATICINIOS', 400, 80.0, 8.0, 6.0 FROM DUAL UNION ALL
    SELECT 'MACA', 'FRUTA', 52, 0.3, 13.8, 0.2 FROM DUAL UNION ALL
    SELECT 'MAMAO', 'FRUTA', 45, 0.8, 11.6, 0.1 FROM DUAL UNION ALL
    SELECT 'MORANGO', 'FRUTA', 32, 0.7, 7.7, 0.3 FROM DUAL UNION ALL
    SELECT 'ABACATE', 'FRUTA', 160, 2.0, 8.5, 14.7 FROM DUAL UNION ALL
    SELECT 'BROCOLIS COZIDO', 'VEGETAL', 35, 2.4, 7.2, 0.4 FROM DUAL UNION ALL
    SELECT 'ALFACE', 'VEGETAL', 15, 1.4, 2.9, 0.2 FROM DUAL UNION ALL
    SELECT 'TOMATE', 'VEGETAL', 18, 0.9, 3.9, 0.2 FROM DUAL UNION ALL
    SELECT 'CENOURA COZIDA', 'VEGETAL', 35, 0.8, 8.2, 0.2 FROM DUAL UNION ALL
    SELECT 'GRAO DE BICO COZIDO', 'LEGUMINOSA', 164, 8.9, 27.4, 2.6 FROM DUAL UNION ALL
    SELECT 'LENTILHA COZIDA', 'LEGUMINOSA', 116, 9.0, 20.1, 0.4 FROM DUAL UNION ALL
    SELECT 'AMENDOIM', 'OLEAGINOSA', 567, 25.8, 16.1, 49.2 FROM DUAL UNION ALL
    SELECT 'CASTANHA DE CAJU', 'OLEAGINOSA', 553, 18.2, 30.2, 43.9 FROM DUAL UNION ALL
    SELECT 'AZEITE DE OLIVA', 'OLEAGINOSA', 884, 0.0, 0.0, 100.0 FROM DUAL UNION ALL
    SELECT 'CAFE SEM ACUCAR', 'BEBIDA', 2, 0.1, 0.0, 0.0 FROM DUAL UNION ALL
    SELECT 'SUCO DE LARANJA', 'BEBIDA', 45, 0.7, 10.4, 0.2 FROM DUAL
) src
ON (i.NOM_INGREDIENTE = src.nome)
WHEN NOT MATCHED THEN
    INSERT (
        NOM_INGREDIENTE,
        ID_CATEGORIA,
        KCAL_100G,
        PROT_100G,
        CARB_100G,
        GORD_100G
    )
    VALUES (
        src.nome,
        (SELECT ID_CATEGORIA
           FROM CATEGORIA_INGREDIENTE
          WHERE NOM_CATEGORIA = src.categoria),
        src.kcal,
        src.prot,
        src.carb,
        src.gord
    );

COMMIT;

-- Refeicoes adicionais
INSERT ALL
    INTO REFEICAO (ID_REFEICAO, ID_USUARIO, DT_REF, ID_TIPO_REFEICAO, OBS)
        VALUES (200, 100, TRUNC(SYSDATE)-6+12/24, 101, 'Almoco Carlos treino 1')
    INTO REFEICAO (ID_REFEICAO, ID_USUARIO, DT_REF, ID_TIPO_REFEICAO, OBS)
        VALUES (201, 100, TRUNC(SYSDATE)-5+12/24, 101, 'Almoco Carlos treino 2')
    INTO REFEICAO (ID_REFEICAO, ID_USUARIO, DT_REF, ID_TIPO_REFEICAO, OBS)
        VALUES (202, 101, TRUNC(SYSDATE)-4+12/24, 101, 'Almoco Ana treino 1')
    INTO REFEICAO (ID_REFEICAO, ID_USUARIO, DT_REF, ID_TIPO_REFEICAO, OBS)
        VALUES (203, 102, TRUNC(SYSDATE)-3+12/24, 101, 'Almoco Maria treino 1')
    INTO REFEICAO (ID_REFEICAO, ID_USUARIO, DT_REF, ID_TIPO_REFEICAO, OBS)
        VALUES (204, 100, TRUNC(SYSDATE)-2+12/24, 101, 'Almoco Carlos treino 3')
    INTO REFEICAO (ID_REFEICAO, ID_USUARIO, DT_REF, ID_TIPO_REFEICAO, OBS)
        VALUES (205, 101, TRUNC(SYSDATE)-1+12/24, 101, 'Almoco Ana treino 2')
    INTO REFEICAO (ID_REFEICAO, ID_USUARIO, DT_REF, ID_TIPO_REFEICAO, OBS)
        VALUES (206, 100, TRUNC(SYSDATE)-6+7/24, 100, 'Cafe Carlos treino 1')
    INTO REFEICAO (ID_REFEICAO, ID_USUARIO, DT_REF, ID_TIPO_REFEICAO, OBS)
        VALUES (207, 101, TRUNC(SYSDATE)-5+7/24, 100, 'Cafe Ana treino 1')
    INTO REFEICAO (ID_REFEICAO, ID_USUARIO, DT_REF, ID_TIPO_REFEICAO, OBS)
        VALUES (208, 102, TRUNC(SYSDATE)-4+7/24, 100, 'Cafe Maria treino 1')
    INTO REFEICAO (ID_REFEICAO, ID_USUARIO, DT_REF, ID_TIPO_REFEICAO, OBS)
        VALUES (209, 101, TRUNC(SYSDATE)-3+15/24, 102, 'Lanche Ana treino 1')
    INTO REFEICAO (ID_REFEICAO, ID_USUARIO, DT_REF, ID_TIPO_REFEICAO, OBS)
        VALUES (210, 102, TRUNC(SYSDATE)-2+15/24, 102, 'Lanche Maria treino 1')
    INTO REFEICAO (ID_REFEICAO, ID_USUARIO, DT_REF, ID_TIPO_REFEICAO, OBS)
        VALUES (211, 100, TRUNC(SYSDATE)-1+19/24, 103, 'Jantar Carlos treino 1')
    INTO REFEICAO (ID_REFEICAO, ID_USUARIO, DT_REF, ID_TIPO_REFEICAO, OBS)
        VALUES (212, 102, TRUNC(SYSDATE)-6+19/24, 103, 'Jantar Maria treino 1')
    INTO REFEICAO (ID_REFEICAO, ID_USUARIO, DT_REF, ID_TIPO_REFEICAO, OBS)
        VALUES (213, 101, TRUNC(SYSDATE)-5+19/24, 103, 'Jantar Ana treino 1')
SELECT 1 FROM DUAL

COMMIT

-- Itens adicionais: almoco tende a combinar arroz, feijao e frango.
-- Cafe/lanche tendem a combinar banana e leite.
-- Jantar tende a combinar arroz e frango.
INSERT ALL
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (200, 200, 100, 150)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (201, 200, 101, 100)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (202, 200, 102, 180)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (203, 201, 100, 140)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (204, 201, 101, 120)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (205, 201, 102, 160)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (206, 202, 100, 120)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (207, 202, 101, 100)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (208, 202, 103, 100)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (209, 203, 100, 130)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (210, 203, 101, 100)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (211, 203, 102, 150)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (212, 204, 100, 150)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (213, 204, 101, 100)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (214, 204, 102, 200)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (215, 205, 100, 100)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (216, 205, 101, 100)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (217, 205, 103, 100)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (218, 206, 104, 100)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (219, 206, 105, 200)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (220, 207, 104, 120)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (221, 207, 105, 200)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (222, 208, 103, 100)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (223, 208, 105, 200)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (224, 209, 104, 120)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (225, 209, 105, 200)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (226, 210, 104, 120)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (227, 210, 103, 100)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (228, 211, 100, 130)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (229, 211, 102, 180)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (230, 212, 100, 120)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (231, 212, 102, 150)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (232, 213, 101, 100)
    INTO REFEICAO_ITEM (ID_ITEM, ID_REFEICAO, ID_INGREDIENTE, QTDE_G) VALUES (233, 213, 102, 140)
SELECT 1 FROM DUAL

COMMIT

-- Evidencia rapida para print/video
SELECT TIPO_REFEICAO,
       ALIMENTO_SUGERIDO,
       FREQUENCIA,
       CONFIANCA_PCT || '%' AS CONFIANCA
FROM VW_SUGESTOES_REFEICAO
ORDER BY TIPO_REFEICAO, CONFIANCA_PCT DESC, FREQUENCIA DESC
