-- OBS: Tabelas e dados já criados anteriormente nas Sprints 1 e 2

CREATE OR REPLACE FUNCTION FUN_REFEICAO_JSON (
    p_id_refeicao NUMBER
) RETURN CLOB
IS
    v_json CLOB := '';
BEGIN
    FOR rec IN (
        SELECT r.ID_REFEICAO,
               u.NOM_USUARIO,
               t.NOM_TIPO,
               r.DT_REF
        FROM REFEICAO r
        JOIN USUARIO u ON u.ID_USUARIO = r.ID_USUARIO
        JOIN TIPO_REFEICAO t ON t.ID_TIPO_REFEICAO = r.ID_TIPO_REFEICAO
        WHERE r.ID_REFEICAO = p_id_refeicao
    )
    LOOP
        v_json := '{' ||
                  '"id_refeicao": ' || rec.ID_REFEICAO || ',' ||
                  '"usuario": "' || rec.NOM_USUARIO || '",' ||
                  '"tipo": "' || rec.NOM_TIPO || '",' ||
                  '"data": "' || TO_CHAR(rec.DT_REF, 'YYYY-MM-DD') || '"' ||
                  '}';
    END LOOP;
 
    RETURN v_json;
 
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'Erro: Refeição não encontrada';
    WHEN OTHERS THEN
        RETURN 'Erro inesperado';
END;
/
 

INSERT INTO PERFIL (NOM_PERFIL) VALUES ('NUTRICIONISTA');
INSERT INTO PERFIL (NOM_PERFIL) VALUES ('PREMIUM');
INSERT INTO PERFIL (NOM_PERFIL) VALUES ('MODERADOR');
 
INSERT INTO UNIDADE (NOM_UNIDADE, SIGLA, TIPO) VALUES ('Quilograma','KG','G');
INSERT INTO UNIDADE (NOM_UNIDADE, SIGLA, TIPO) VALUES ('Litro','L','ML');
 
INSERT INTO NUTRIENTE (NOM_NUTRIENTE) VALUES ('FIBRA');
 
INSERT INTO CATEGORIA_INGREDIENTE (NOM_CATEGORIA) VALUES ('FRUTA');
INSERT INTO CATEGORIA_INGREDIENTE (NOM_CATEGORIA) VALUES ('LATICINIO');
 
INSERT INTO TIPO_REFEICAO (NOM_TIPO) VALUES ('CEIA');
 
INSERT INTO USUARIO (NOM_USUARIO, EMAIL, DT_NASC) VALUES ('Ana Silva','ana@fiap.com', DATE '1995-05-10');
INSERT INTO USUARIO (NOM_USUARIO, EMAIL, DT_NASC) VALUES ('Carlos Lima','carlos@fiap.com', DATE '1998-03-22');
INSERT INTO USUARIO (NOM_USUARIO, EMAIL, DT_NASC) VALUES ('Maria Santos','maria@fiap.com', DATE '2001-07-15');
INSERT INTO USUARIO (NOM_USUARIO, EMAIL, DT_NASC) VALUES ('Pedro Costa','pedro@fiap.com', DATE '1999-11-30');
 
INSERT INTO INGREDIENTE (NOM_INGREDIENTE, ID_CATEGORIA) VALUES ('FEIJAO COZIDO', (SELECT ID_CATEGORIA FROM CATEGORIA_INGREDIENTE WHERE NOM_CATEGORIA='CEREAL'));
INSERT INTO INGREDIENTE (NOM_INGREDIENTE, ID_CATEGORIA) VALUES ('FRANGO GRELHADO', (SELECT ID_CATEGORIA FROM CATEGORIA_INGREDIENTE WHERE NOM_CATEGORIA='CARNE'));
INSERT INTO INGREDIENTE (NOM_INGREDIENTE, ID_CATEGORIA) VALUES ('BANANA', (SELECT ID_CATEGORIA FROM CATEGORIA_INGREDIENTE WHERE NOM_CATEGORIA='FRUTA'));
INSERT INTO INGREDIENTE (NOM_INGREDIENTE, ID_CATEGORIA) VALUES ('LEITE INTEGRAL', (SELECT ID_CATEGORIA FROM CATEGORIA_INGREDIENTE WHERE NOM_CATEGORIA='LATICINIO'));
 
COMMIT;
 
INSERT INTO INGREDIENTE_NUTRIENTE (ID_INGREDIENTE, ID_NUTRIENTE, ID_UNIDADE_BASE, BASE_QTD, VALOR_POR_BASE)
SELECT i.ID_INGREDIENTE, n.ID_NUTRIENTE, u.ID_UNIDADE, 100,
       CASE n.NOM_NUTRIENTE
         WHEN 'CALORIA' THEN 77
         WHEN 'PROTEINA' THEN 5.0
         WHEN 'CARBOIDRATO' THEN 14.0
         WHEN 'GORDURA' THEN 0.5
       END
  FROM INGREDIENTE i
  JOIN NUTRIENTE n ON n.NOM_NUTRIENTE IN ('CALORIA','PROTEINA','CARBOIDRATO','GORDURA')
  JOIN UNIDADE u ON u.SIGLA='G'
 WHERE i.NOM_INGREDIENTE='FEIJAO COZIDO';
 
INSERT INTO INGREDIENTE_NUTRIENTE (ID_INGREDIENTE, ID_NUTRIENTE, ID_UNIDADE_BASE, BASE_QTD, VALOR_POR_BASE)
SELECT i.ID_INGREDIENTE, n.ID_NUTRIENTE, u.ID_UNIDADE, 100,
       CASE n.NOM_NUTRIENTE
         WHEN 'CALORIA' THEN 159
         WHEN 'PROTEINA' THEN 32.0
         WHEN 'CARBOIDRATO' THEN 0.0
         WHEN 'GORDURA' THEN 3.6
       END
  FROM INGREDIENTE i
  JOIN NUTRIENTE n ON n.NOM_NUTRIENTE IN ('CALORIA','PROTEINA','CARBOIDRATO','GORDURA')
  JOIN UNIDADE u ON u.SIGLA='G'
 WHERE i.NOM_INGREDIENTE='FRANGO GRELHADO';
 
INSERT INTO INGREDIENTE_NUTRIENTE (ID_INGREDIENTE, ID_NUTRIENTE, ID_UNIDADE_BASE, BASE_QTD, VALOR_POR_BASE)
SELECT i.ID_INGREDIENTE, n.ID_NUTRIENTE, u.ID_UNIDADE, 100,
       CASE n.NOM_NUTRIENTE
         WHEN 'CALORIA' THEN 89
         WHEN 'PROTEINA' THEN 1.1
         WHEN 'CARBOIDRATO' THEN 22.8
         WHEN 'GORDURA' THEN 0.3
       END
  FROM INGREDIENTE i
  JOIN NUTRIENTE n ON n.NOM_NUTRIENTE IN ('CALORIA','PROTEINA','CARBOIDRATO','GORDURA')
  JOIN UNIDADE u ON u.SIGLA='G'
 WHERE i.NOM_INGREDIENTE='BANANA';
 
INSERT INTO INGREDIENTE_NUTRIENTE (ID_INGREDIENTE, ID_NUTRIENTE, ID_UNIDADE_BASE, BASE_QTD, VALOR_POR_BASE)
SELECT i.ID_INGREDIENTE, n.ID_NUTRIENTE, u.ID_UNIDADE, 100,
       CASE n.NOM_NUTRIENTE
         WHEN 'CALORIA' THEN 60
         WHEN 'PROTEINA' THEN 3.2
         WHEN 'CARBOIDRATO' THEN 4.7
         WHEN 'GORDURA' THEN 3.3
       END
  FROM INGREDIENTE i
  JOIN NUTRIENTE n ON n.NOM_NUTRIENTE IN ('CALORIA','PROTEINA','CARBOIDRATO','GORDURA')
  JOIN UNIDADE u ON u.SIGLA='ML'
 WHERE i.NOM_INGREDIENTE='LEITE INTEGRAL';
 
COMMIT;
 
INSERT INTO REFEICAO (ID_USUARIO, DT_REF, ID_TIPO_REFEICAO, OBS)
SELECT (SELECT ID_USUARIO FROM USUARIO WHERE EMAIL='ana@fiap.com'),
       TRUNC(SYSDATE) + 7/24,
       (SELECT ID_TIPO_REFEICAO FROM TIPO_REFEICAO WHERE NOM_TIPO='CAFE'),
       'Cafe da manha'
FROM dual;
 
INSERT INTO REFEICAO (ID_USUARIO, DT_REF, ID_TIPO_REFEICAO, OBS)
SELECT (SELECT ID_USUARIO FROM USUARIO WHERE EMAIL='carlos@fiap.com'),
       TRUNC(SYSDATE) + 12/24,
       (SELECT ID_TIPO_REFEICAO FROM TIPO_REFEICAO WHERE NOM_TIPO='ALMOCO'),
       'Almoco completo'
FROM dual;
 
INSERT INTO REFEICAO (ID_USUARIO, DT_REF, ID_TIPO_REFEICAO, OBS)
SELECT (SELECT ID_USUARIO FROM USUARIO WHERE EMAIL='maria@fiap.com'),
       TRUNC(SYSDATE) + 15/24,
       (SELECT ID_TIPO_REFEICAO FROM TIPO_REFEICAO WHERE NOM_TIPO='LANCHE'),
       'Lanche da tarde'
FROM dual;
 
INSERT INTO REFEICAO (ID_USUARIO, DT_REF, ID_TIPO_REFEICAO, OBS)
SELECT (SELECT ID_USUARIO FROM USUARIO WHERE EMAIL='pedro@fiap.com'),
       TRUNC(SYSDATE) + 19/24,
       (SELECT ID_TIPO_REFEICAO FROM TIPO_REFEICAO WHERE NOM_TIPO='JANTAR'),
       'Jantar leve'
FROM dual;
 
COMMIT;
 
INSERT INTO REFEICAO_ITEM (ID_REFEICAO, ID_INGREDIENTE, QTDE, ID_UNIDADE)
SELECT r.ID_REFEICAO, i.ID_INGREDIENTE, 200, (SELECT ID_UNIDADE FROM UNIDADE WHERE SIGLA='ML')
  FROM REFEICAO r
  JOIN USUARIO u ON u.ID_USUARIO = r.ID_USUARIO
  JOIN INGREDIENTE i ON i.NOM_INGREDIENTE='LEITE INTEGRAL'
 WHERE u.EMAIL='ana@fiap.com'
   AND r.OBS='Cafe da manha';
 
INSERT INTO REFEICAO_ITEM (ID_REFEICAO, ID_INGREDIENTE, QTDE, ID_UNIDADE)
SELECT r.ID_REFEICAO, i.ID_INGREDIENTE, 150, (SELECT ID_UNIDADE FROM UNIDADE WHERE SIGLA='G')
  FROM REFEICAO r
  JOIN USUARIO u ON u.ID_USUARIO = r.ID_USUARIO
  JOIN INGREDIENTE i ON i.NOM_INGREDIENTE='FRANGO GRELHADO'
 WHERE u.EMAIL='carlos@fiap.com'
   AND r.OBS='Almoco completo';
 
INSERT INTO REFEICAO_ITEM (ID_REFEICAO, ID_INGREDIENTE, QTDE, ID_UNIDADE)
SELECT r.ID_REFEICAO, i.ID_INGREDIENTE, 100, (SELECT ID_UNIDADE FROM UNIDADE WHERE SIGLA='G')
  FROM REFEICAO r
  JOIN USUARIO u ON u.ID_USUARIO = r.ID_USUARIO
  JOIN INGREDIENTE i ON i.NOM_INGREDIENTE='FEIJAO COZIDO'
 WHERE u.EMAIL='carlos@fiap.com'
   AND r.OBS='Almoco completo';
 
INSERT INTO REFEICAO_ITEM (ID_REFEICAO, ID_INGREDIENTE, QTDE, ID_UNIDADE)
SELECT r.ID_REFEICAO, i.ID_INGREDIENTE, 120, (SELECT ID_UNIDADE FROM UNIDADE WHERE SIGLA='G')
  FROM REFEICAO r
  JOIN USUARIO u ON u.ID_USUARIO = r.ID_USUARIO
  JOIN INGREDIENTE i ON i.NOM_INGREDIENTE='BANANA'
 WHERE u.EMAIL='maria@fiap.com'
   AND r.OBS='Lanche da tarde';
 
INSERT INTO REFEICAO_ITEM (ID_REFEICAO, ID_INGREDIENTE, QTDE, ID_UNIDADE)
SELECT r.ID_REFEICAO, i.ID_INGREDIENTE, 180, (SELECT ID_UNIDADE FROM UNIDADE WHERE SIGLA='G')
  FROM REFEICAO r
  JOIN USUARIO u ON u.ID_USUARIO = r.ID_USUARIO
  JOIN INGREDIENTE i ON i.NOM_INGREDIENTE='FRANGO GRELHADO'
 WHERE u.EMAIL='pedro@fiap.com'
   AND r.OBS='Jantar leve';
 
COMMIT;


INSERT INTO USUARIO (NOM_USUARIO, EMAIL, DT_NASC) VALUES ('Julia Ferreira','julia@fiap.com', DATE '2000-09-18');

INSERT INTO INGREDIENTE (NOM_INGREDIENTE, ID_CATEGORIA) 
VALUES ('ARROZ BRANCO', (SELECT ID_CATEGORIA FROM CATEGORIA_INGREDIENTE WHERE NOM_CATEGORIA='CEREAL'));

INSERT INTO REFEICAO (ID_USUARIO, DT_REF, ID_TIPO_REFEICAO, OBS)
SELECT (SELECT ID_USUARIO FROM USUARIO WHERE EMAIL='julia@fiap.com'),
       TRUNC(SYSDATE) + 21/24,
       (SELECT ID_TIPO_REFEICAO FROM TIPO_REFEICAO WHERE NOM_TIPO='CEIA'),
       'Ceia leve'
FROM dual;

COMMIT;

INSERT INTO REFEICAO_ITEM (ID_REFEICAO, ID_INGREDIENTE, QTDE, ID_UNIDADE)
SELECT r.ID_REFEICAO, i.ID_INGREDIENTE, 150, (SELECT ID_UNIDADE FROM UNIDADE WHERE SIGLA='G')
  FROM REFEICAO r
  JOIN USUARIO u ON u.ID_USUARIO = r.ID_USUARIO
  JOIN INGREDIENTE i ON i.NOM_INGREDIENTE='ARROZ BRANCO'
 WHERE u.EMAIL='julia@fiap.com'
   AND r.OBS='Ceia leve';

COMMIT;
 

CREATE OR REPLACE PROCEDURE PRC_RELATORIO_REFEICOES_JSON (
    p_id_usuario IN NUMBER
) AS
    v_json CLOB;
    v_count NUMBER;
    v_usuario VARCHAR2(100);
BEGIN
    IF p_id_usuario IS NULL THEN
        RAISE_APPLICATION_ERROR(-20501, 'ID do usuario e obrigatorio');
    END IF;
 
    SELECT COUNT(*) INTO v_count FROM USUARIO WHERE ID_USUARIO = p_id_usuario;
    IF v_count = 0 THEN
        RAISE NO_DATA_FOUND;
    END IF;
 
    SELECT NOM_USUARIO INTO v_usuario FROM USUARIO WHERE ID_USUARIO = p_id_usuario;
 
    DBMS_OUTPUT.PUT_LINE('Refeicoes do usuario: ' || v_usuario);
    DBMS_OUTPUT.PUT_LINE('----------------------------------------');
 
    v_count := 0;
    FOR rec IN (
        SELECT r.ID_REFEICAO
          FROM REFEICAO r
          JOIN USUARIO u ON u.ID_USUARIO = r.ID_USUARIO
          JOIN TIPO_REFEICAO t ON t.ID_TIPO_REFEICAO = r.ID_TIPO_REFEICAO
         WHERE r.ID_USUARIO = p_id_usuario
         ORDER BY r.DT_REF
    ) LOOP
        v_json := FUN_REFEICAO_JSON(rec.ID_REFEICAO);
        DBMS_OUTPUT.PUT_LINE(v_json);
        v_count := v_count + 1;
    END LOOP;
 
    IF v_count = 0 THEN
        DBMS_OUTPUT.PUT_LINE('Nenhuma refeicao encontrada para este usuario.');
    END IF;
 
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Erro: Usuario nao encontrado.');
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Erro: Valor invalido informado.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Erro inesperado: ' || SQLERRM);
END;
/
 

CREATE OR REPLACE PROCEDURE PRC_NUTRIENTES_ANTERIOR_PROXIMO AS
    TYPE t_id_ing IS TABLE OF NUMBER;
    TYPE t_id_nut IS TABLE OF NUMBER;
    TYPE t_valor IS TABLE OF NUMBER;
    
    v_ids_ing t_id_ing;
    v_ids_nut t_id_nut;
    v_valores t_valor;
    v_anterior VARCHAR2(20);
    v_proximo VARCHAR2(20);
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM INGREDIENTE_NUTRIENTE;
    
    IF v_count = 0 THEN
        RAISE NO_DATA_FOUND;
    END IF;
 
    SELECT ID_INGREDIENTE, ID_NUTRIENTE, VALOR_POR_BASE
      BULK COLLECT INTO v_ids_ing, v_ids_nut, v_valores
      FROM INGREDIENTE_NUTRIENTE
     ORDER BY ID_INGREDIENTE, ID_NUTRIENTE;
 
    DBMS_OUTPUT.PUT_LINE(RPAD('INGREDIENTE',15) || RPAD('NUTRIENTE',15) || RPAD('ANTERIOR',15) || RPAD('ATUAL',15) || RPAD('PROXIMO',15));
    DBMS_OUTPUT.PUT_LINE('------------------------------------------------------------------------');
 
    FOR i IN 1..v_valores.COUNT LOOP
        IF i = 1 THEN
            v_anterior := 'Vazio';
        ELSE
            v_anterior := TO_CHAR(v_valores(i-1));
        END IF;
 
        IF i = v_valores.COUNT THEN
            v_proximo := 'Vazio';
        ELSE
            v_proximo := TO_CHAR(v_valores(i+1));
        END IF;
 
        DBMS_OUTPUT.PUT_LINE(
            RPAD(v_ids_ing(i),15) ||
            RPAD(v_ids_nut(i),15) ||
            RPAD(v_anterior,15) ||
            RPAD(TO_CHAR(v_valores(i)),15) ||
            RPAD(v_proximo,15)
        );
    END LOOP;
 
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Erro: Nenhum registro encontrado.');
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Erro: Problema na conversao de valores.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Erro inesperado: ' || SQLERRM);
END;
/
 

CREATE OR REPLACE FUNCTION FUN_CALC_CALORIAS_REFEICAO (
    p_id_refeicao NUMBER
) RETURN NUMBER
IS
    v_total NUMBER := 0;
    v_count NUMBER;
BEGIN
    IF p_id_refeicao IS NULL THEN
        RAISE_APPLICATION_ERROR(-20601, 'ID da refeicao e obrigatorio');
    END IF;
 
    SELECT COUNT(*) INTO v_count FROM REFEICAO WHERE ID_REFEICAO = p_id_refeicao;
    IF v_count = 0 THEN
        RAISE NO_DATA_FOUND;
    END IF;
 
    SELECT NVL(SUM((ri.QTDE / inut.BASE_QTD) * inut.VALOR_POR_BASE), 0)
      INTO v_total
      FROM REFEICAO_ITEM ri
      JOIN INGREDIENTE_NUTRIENTE inut ON inut.ID_INGREDIENTE = ri.ID_INGREDIENTE
                                     AND inut.ID_UNIDADE_BASE = ri.ID_UNIDADE
      JOIN NUTRIENTE n ON n.ID_NUTRIENTE = inut.ID_NUTRIENTE
     WHERE ri.ID_REFEICAO = p_id_refeicao
       AND n.NOM_NUTRIENTE = 'CALORIA';
 
    RETURN ROUND(v_total, 2);
 
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN -1;
    WHEN VALUE_ERROR THEN
        RETURN -2;
    WHEN OTHERS THEN
        RETURN -99;
END;
/
 

CREATE TABLE AUDITORIA_INGREDIENTE (
    ID_AUDITORIA    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    OPERACAO        VARCHAR2(10) NOT NULL,
    USUARIO_BD      VARCHAR2(100) NOT NULL,
    DT_OPERACAO     DATE DEFAULT SYSDATE NOT NULL,
    OLD_ID          NUMBER,
    OLD_NOME        VARCHAR2(120),
    OLD_CATEGORIA   NUMBER,
    NEW_ID          NUMBER,
    NEW_NOME        VARCHAR2(120),
    NEW_CATEGORIA   NUMBER,
    CONSTRAINT PK_AUDITORIA_ING PRIMARY KEY (ID_AUDITORIA)
);
 
 
CREATE OR REPLACE TRIGGER TRG_AUDITORIA_INGREDIENTE
AFTER INSERT OR UPDATE OR DELETE ON INGREDIENTE
FOR EACH ROW
DECLARE
    v_operacao VARCHAR2(10);
BEGIN
    IF INSERTING THEN
        v_operacao := 'INSERT';
    ELSIF UPDATING THEN
        v_operacao := 'UPDATE';
    ELSE
        v_operacao := 'DELETE';
    END IF;
 
    INSERT INTO AUDITORIA_INGREDIENTE (
        OPERACAO, USUARIO_BD, DT_OPERACAO,
        OLD_ID, OLD_NOME, OLD_CATEGORIA,
        NEW_ID, NEW_NOME, NEW_CATEGORIA
    ) VALUES (
        v_operacao, USER, SYSDATE,
        :OLD.ID_INGREDIENTE, :OLD.NOM_INGREDIENTE, :OLD.ID_CATEGORIA,
        :NEW.ID_INGREDIENTE, :NEW.NOM_INGREDIENTE, :NEW.ID_CATEGORIA
    );
END;
/
 

-- FUNCAO 1 (JSON) 
SELECT FUN_REFEICAO_JSON(1) FROM DUAL;
 
-- PROCEDIMENTO 1 (RELATORIO JSON) 
SET SERVEROUTPUT ON;
EXEC PRC_RELATORIO_REFEICOES_JSON(1);
 
-- PROCEDIMENTO 2 (ANTERIOR/ATUAL/PROXIMO)
SET SERVEROUTPUT ON;
EXEC PRC_NUTRIENTES_ANTERIOR_PROXIMO;
 
-- FUNCAO 2 (CALORIAS) 
SELECT FUN_CALC_CALORIAS_REFEICAO(1) FROM DUAL;
 
-- TRIGGER (AUDITORIA) 
INSERT INTO INGREDIENTE (NOM_INGREDIENTE, ID_CATEGORIA) VALUES ('OVO COZIDO', (SELECT ID_CATEGORIA FROM CATEGORIA_INGREDIENTE WHERE NOM_CATEGORIA='CARNE'));
UPDATE INGREDIENTE SET NOM_INGREDIENTE = 'OVO COZIDO INTEIRO' WHERE NOM_INGREDIENTE = 'OVO COZIDO';
DELETE FROM INGREDIENTE WHERE NOM_INGREDIENTE = 'OVO COZIDO INTEIRO';
COMMIT;
SELECT * FROM AUDITORIA_INGREDIENTE;
 